Created PDF report generation scripts
ebradley12/Band-Camp-Tracker pull request #68
Opened 2024-12-04 15:32 UTC by ebradley12

This pull request refers to ticket #38 

This pull request introduces a script to generate a daily sales report in PDF format, summarising key sales metrics such as total transactions, total sales, top genres, top artists, and top regions. The report is generated for the previous day, uploaded to an S3 bucket, and emailed to recipients using AWS services.

2024-12-04 15:34 UTC, emily-curtis commented on reports/report_generator.py
> +    """Generate a PDF report containing sales data."""
Could we have type hints?

2024-12-04 15:34 UTC, emily-curtis commented on reports/report_generator.py
> +
Great use of logging!!

2024-12-04 15:38 UTC, ebradley12 commented on reports/report_generator.py
> +    """Generate a PDF report containing sales data."""
Yes ofc how could I forget!

2024-12-05 10:31 UTC, lukieh2014 commented
we could add a couple graphs to the report, to visualise the data ?

2024-12-06 16:53 UTC, GabrielNsiah commented on reports/graphs.py
> +    Generate a bar chart.
Could this docstring be more descriptive?

2024-12-09 09:51 UTC, bentrzcinski requested changes
Really nice code, I particularly like the separate queries script.

2024-12-09 09:51 UTC, bentrzcinski commented on docker/pipeline_dockerfile
> +CMD ["python", "etl.py"]
Is this related to the pull request? We already have a dockerfile for this in pipline (and this needs to be a lambda dockerfile)

2024-12-09 09:51 UTC, bentrzcinski commented on reports/emailer.py
> +            'ses', region_name=environ.get('AWS_REGION', 'us-east-1'))
```suggestion
            'ses', region_name=environ.get('AWS_REGION', 'eu-west-2'))
```

2024-12-09 09:51 UTC, bentrzcinski commented on reports/emailer.py
> +        raise
If the custom error messages are the same, these exceptions can be caught in the same line: 
```suggestion
    except (ClientError, Exception) as e:
        logging.error("Failed to send email: %s", e)
        raise
```

2024-12-09 09:51 UTC, bentrzcinski commented on reports/graphs.py
> +"""
```suggestion
"""
This script provides functions for generating visualisations as part of the PDF Report.
"""
```

2024-12-09 09:51 UTC, bentrzcinski commented on reports/graphs.py
> +    except Exception as e:
Could we make this a more specific exception?

2024-12-09 09:51 UTC, bentrzcinski commented on reports/lambda_handler.py
> +        )
Could logging config be done in its own function?

2024-12-09 09:51 UTC, bentrzcinski commented on reports/lambda_handler.py
> +        return {"statusCode": 400, "body": "Validation Error: %s" % ve}
Can we only get 200 or 400 codes? What if the server can't be found?

2024-12-09 09:51 UTC, bentrzcinski commented on reports/queries.py
> +        logging.warning("The database %s doesn't exist", environ["DB_NAME"])
What is DB_NAME isn't defined? We don't want the error handling throwing an error

2024-12-09 09:51 UTC, bentrzcinski commented on reports/report_generator.py
> +    except ValueError as e:
Could we have a more specific exception type?

2024-12-09 09:51 UTC, bentrzcinski commented on reports/report_generator.py
> +    except ValueError as e:
more specific exception type?

2024-12-09 09:51 UTC, bentrzcinski commented on reports/report_generator.py
> +    except ValueError as e:
Could we have a more specific exception type here?

2024-12-09 09:51 UTC, bentrzcinski commented on reports/report_generator.py
> +    except Exception as e:
How about a specific exception type here for likely errors?

2024-12-09 09:51 UTC, bentrzcinski commented on reports/report_generator.py
> +    except Exception as e:
Could we have a more specific exception type here?

2024-12-09 09:51 UTC, bentrzcinski commented on reports/report_generator.py
> +    pdf_file = generate_daily_report()
Do we want to save this to a variable here?

2024-12-09 10:45 UTC, bentrzcinski approved these changes
Looks good! Nice changes

2024-12-09 10:46 UTC, merged